/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * My shiny API
 * My shiny API description
 * OpenAPI spec version: v0.0.1
 */

export interface Episode {
  id?: number;
  showId?: number;
  number?: number;
  season?: number;
  networkId?: number;
  rating?: number;
  name?: string;
  airdate?: string;
  showName?: string;
}
