/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * My shiny API
 * My shiny API description
 * OpenAPI spec version: v0.0.1
 */

export interface Show {
  rating?: number;
  showName?: string;
  summary?: string;
  networkId?: number;
  id?: number;
  episodeCount?: number;
  releasedEpisodeCount?: number;
  genres?: string[];
}
