/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * My shiny API
 * My shiny API description
 * OpenAPI spec version: v0.0.1
 */

export interface ShowTime {
  time?: string;
  days?: string[];
}
